name: DreamSpeed
main: main.java.com.thedreamsanctuary.dreamspeed.DreamSpeed
version: 1.0.0-SNAPSHOT
authors: [Ajcool1050]
description: DreamSpeed, Tell the speed of your dreams.

commands:
    dreamspeed:
        aliases: dspeed
        permission: dreamspeed.use
        description: View live updating server stats
 
permissions:
    dreamspeed.use:
        default: false
